# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
          with:
            php-version: "8.0"
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Install phpDocumentor
        run: |
          curl --silent --location "https://phpdoc.org/phpDocumentor.phar" > "phpDocumentor.phar"
          chmod a+x phpdoc.phar
      - name: Generate Documentation
        run: php phpDocumentor.phar --directory="." --target="build"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload build directory only
          path: 'build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
